name: PartyPlugin
version: 1.1.0
main: com.party.PartyPlugin
api-version: 1.21
description: Plugin Minecraft per gestione party complessi con ruoli e chat privata
author: GiuseppeNetta

commands:
  party:
    description: Gestione party
    usage: /party <subcommand>
    aliases: [p]
    permission: party.use
